### PR TITLE
Add missing support for IPv6 link local addresses

### PR DESCRIPTION
**Pull request by syenna**
Add missing support for IPv6 link local addresses (which include % followed by the interface name)

### CODE REVIEW

**Comment by hintjens** [comment]
Can you please make this change in libzmq master, thank you.

**Comment by syenna** [comment]
Sure, I will do that as well.

**Comment by syenna** [comment]
Is this declined on zeromq4-1?

Please consider this as a bug fix on zeromq4-1 as IPv6 link local addresses do not work on this version.

**Comment by hintjens** [comment]
It's not declined; we have a process for bug fixes however:

- file an issue on the libzmq issue tracker
- make the bug fix on libzmq master
- backport the bug fix to stable

Thanks.

**Comment by syenna** [comment]
Great, I have pushed the fix to libzmq master already.

**Comment by hintjens** [comment]
OK, please make an issue if there's not one already for this. Thanks.

**Comment by syenna** [comment]
I have created an issue #1661 on libzmq issue tracker. You can close that one and accept this pull request on this branch. Thanks!

**Pull request closed without merging**
