### PR TITLE
Backport #1702

### PR DESCRIPTION
**Pull request by Kentzo**

### CODE REVIEW

**Comment by hintjens** [comment]
Would you like to also update NEWS for this backport? Thanks!

**Comment by Kentzo** [comment]
Didn't know that changes to CMake go into NEWS. Do you still need that one?

**Comment by hintjens** [comment]
If there's an issue this deals with, then it's worth telling people about
it. We cover build problems in NEWS as well as code changes.

**Comment by Kentzo** [comment]
It's not a problem… rather missing feature supported by cmake :)

**Pull request merged**
