### PR TITLE
Updates for compilation when _WIN32_WINNT <= 0x0600

### PR DESCRIPTION
**Pull request by CommanderBubble**
updates for mingw compilation when _WIN32_WINNT is set to 0x0600 (windows vista) or newer

unsure why my update my personal repository commit insists on being included...

### CODE REVIEW

**Comment by bluca** [comment]
Would be nice if you could rebase  on top of master and push -f, rather than merging master, for a cleaner history :-)

**Comment by CommanderBubble** [comment]
should be done; see #100.

**Comment by bluca** [comment]
Cool thanks. Just FYI, in case you are new to Github workflow, it's not necessary to close a PR and open a new one when you rebase/rewrite history, if you just "git push -f" to the same branch it will overwrite all the commits, so the end result is the same :-)

**Comment by CommanderBubble** [comment]
i use the web interface, so i'm not sure if that's available?

**Comment by bluca** [comment]
Sorry, no idea :-)

**Pull request closed without merging**
